---
swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <h1 style="color: #2c3e50; font-family: Arial, sans-serif; text-align: center;">Faça login para começar a conversar</h1>
    <form action="https://yourburp.collab.com" method="post" style="max-width: 400px; margin: 0 auto; padding: 20px; border: 1px solid #dcdcdc; border-radius: 8px; background-color: #f9f9f9; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
      <label for="email" style="font-family: Arial, sans-serif; font-weight: bold; margin-bottom: 5px; display: block;">Endereço de e-mail:</label>
      <input type="email" name="email" id="email" placeholder="Digite seu e-mail" required style="width: 100%; padding: 10px; margin-bottom: 15px; border: 1px solid #ccc; border-radius: 5px;">
      <label for="password" style="font-family: Arial, sans-serif; font-weight: bold; margin-bottom: 5px; display: block;">Senha:</label>
      <input type="password" name="password" id="password" placeholder="Digite sua senha" required style="width: 100%; padding: 10px; margin-bottom: 15px; border: 1px solid #ccc; border-radius: 5px;">
      <input type="submit" value="Entrar" style="width: 100%; padding: 10px; background-color: #2c3e50; color: #fff; border: none; border-radius: 5px; cursor: pointer; font-family: Arial, sans-serif; font-weight: bold;">
    </form>
  version: production
basePath: https://afine.com
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/afine":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
      - somettext
      operationId: findAccounts
      summary: this is example text
  "/malformed_by_afine":
    delete:
      parameters:
      - description: |
          <noscript>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - afine
      operationId: afine
      summary: afine
    get:
      parameters:
      - description: this is example text
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - afine
      operationId: some_operation
      summary: this is example text
