---
swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <h1>Connectez vous pour commencer à chatter</h1>
    <form action="https://yourburp.collab.com" method="post">
    <label for="email">Adresse e-mail:</label>
    <input name="email">
    <label for="password">Mot de Passe:</label>
    <input name="password">
    <input type="submit" value="Connexion"></form>
  version: production
basePath: https://afine.com
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/afine":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
      - somettext
      operationId: findAccounts
      summary: this is example text
  "/malformed_by_afine":
    delete:
      parameters:
      - description: |
          <noscript>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - afine
      operationId: afine
      summary: afine
    get:
      parameters:
      - description: this is example text
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - afine
      operationId: some_operation
      summary: this is example text
