---
swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <h1>PoC</h1>
  version: production
basePath: https://google.com
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/afine":
    get:
      responses:
        '200':
          description: ENDPOINT de API Falso.
      tags:
      - somettext
      operationId: findAccounts
      summary: Exemplo de ataque no ambiente
  "/malformed_by_afine":
    delete:
      parameters:
      - description: |
          <noscript>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: ENDPOINT de API Falso 2.
      tags:
      - afine
      operationId: afine
      summary: afine
    get:
      parameters:
      - description: Exemplo de html Injection
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: <h1></h1>
      tags:
      - afine
      operationId: some_operation
      summary: this is example text
